=== vitalydenisoff/HomeWorkPC/data/comps.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/comps"
        xmlns:tns="http://www.example.com/comps" elementFormDefault="qualified">

    <element name="devices">
        <complexType>
            <sequence>
                <element name="device" type="tns:device" minOccurs="1"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="device">
        <sequence>
            <element name="price" type="nonNegativeInteger"/>
            <element name="type" type="tns:Type"/>
            <element name="critical"/>
        </sequence>
        <attribute name="device" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="powerPack"/>
                    <enumeration value="monitor"/>
                    <enumeration value="harddrive"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Type">
        <sequence>
            <element name="location">
            <restriction base="string">
                <enumeration value="Local"/>
                <enumeration value="Perefirial"/>
            </restriction>
            </element>
            <element name="powerConsum" type="nonNegativeInteger"/>
            <element name="cooler" type="boolean"/>
            <element name="port" type="string">
                <restriction base="string">
                    <enumeration value="VGA"/>
                    <enumeration value="Com"/>
                    <enumeration value="USB"/>
                    <enumeration value="LPT"/>
                </restriction>
            </element>
        </sequence>
    </complexType>
</schema>

=== vitalydenisoff/HomeWorkPC/data/comps.xml
<?xml version="1.0" encoding="UTF-8" ?>

<devices xmlns="http://www.example.org/Comps"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.example.org/stamps comps.xsd">

   <device name="powerPack" origin="China">
       <price>50</price>
       <type>
           <location>Local</location>
           <powerConsum>600</powerConsum>
           <cooler>true</cooler>
           <port>no</port>
       </type>
       <critical>true</critical>
   </device>
    <device name="monitor" origin="China">
        <price>350</price>
        <type>
            <location>Perefirial</location>
            <powerConsum>75</powerConsum>
            <cooler>false</cooler>
            <port>VGA</port>
        </type>
        <critical>false</critical>
    </device>



</devices>

=== vitalydenisoff/HomeWorkPC/src/main/java/org/example/xml/comps.xml
<?xml version="1.0" encoding="UTF-8" ?>

<devices xmlns="http://www.example.org/Comps"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.example.org/stamps comps.xsd">

   <device name="powerPack" origin="China">
       <price>50</price>
       <type>
           <location>Local</location>
           <powerConsum>600</powerConsum>
           <cooler>True</cooler>
           <port>No</port>
       </type>
       <critical>True</critical>
   </device>
    <device name="monitor" origin="China">
        <price>350</price>
        <type>
            <location>Perefirial</location>
            <powerConsum>75</powerConsum>
            <cooler>False</cooler>
            <port>VGA</port>
        </type>
        <critical>False</critical>
    </device>



</devices>
